package arinside.ar.deffile;

import java.util.HashMap;
import java.util.Map;

/**
 * Java port of {@code com.bmc.arsys.server.domain.export.def.DefItemLabel} (ported from the
 * real AR Server) - the fixed-width
 * {@code "   label          : "}-style tag vocabulary used by every {@code .def} export line. A
 * tag is matched by trimming the raw line's tag portion and looking it up here by the label
 * string's own trimmed form (leading/trailing whitespace only - internal padding before the colon
 * is significant and part of the lookup key, since several labels share a short prefix at
 * different indentation widths, e.g. {@code ID} vs {@code ID_2}).
 */
public enum DefItemLabel {
    ENCRYPT_CHAR_SET("  encrypt-char-set:  "),
    FILE_CHAR_SET("char-set: "),
    FILE_EXPORT_TIMESTAMP("export-timestamp: "),
    ACCESS_OPTION("      access-opt  : "),
    FIELD_CHAR_OPTION("      option      : "),
    ACTLINK_FIELD("   actlink-field  : "),
    ACTLINK_FOCUS("   actlink-focus  : "),
    ACTLINK_CONTROL("   actlink-control: "),
    ACTLINK_MASK("   actlink-mask   : "),
    ACTLINK_QRY("   actlink-query  : "),
    ACTLINK_ORD("   actlink-order  : "),
    ADD_INDEX("   add-index      : "),
    ADD_CTNR_OWNER("   add-owning-obj : "),
    ADD_CTNR_SUBADM("   add-ctnr-admn:   "),
    ADD_PERMISSION("   add-permission : "),
    ADD_SCHEMA_NAME("   add-schema-name: "),
    ADD_SCHEMA_SUBADM("   add-schema-admn: "),
    SVC_SERVER("   service-server : "),
    SVC_SCHEMA("   service-schema : "),
    SVC_RQST_MAP("   svc-rqstId-map : "),
    SVC_IN_FLD_MAP("   svc-InFld-map  : "),
    SVC_OUT_FLD_MAP("   svc-OutFld-map : "),
    SVC_SMPL_SERVER(" svc-sampleServer : "),
    SVC_SMPL_SCHEMA(" svc-sampleSchema : "),
    ALLOW_CODES("   allow-codes    : "),
    ADMIN_SUB_PERM("   admin-sub-perm : "),
    AD_COMMAND("   command        : "),
    CALLGUIDE(" call guide :"),
    CHANGE_DIARY("   change-diary   : "),
    CHAR_MENU("   char-menu      : "),
    ENCR_CHAR_MENU(" encrypt-char-menu: "),
    CHAR_MENU_2("      char-menu   : "),
    CLOSE_WND("      close-wnd   : "),
    CLOSE_WND_ALL("      close-all   : "),
    COMMAND("      command     : "),
    ENCR_COMMAND("    encrypt-cmd   : "),
    COMMIT_CHANGES("    commit_changes: "),
    CONTENT("      content     : "),
    CONTAINER_SUBADM("   container-admin: "),
    CORE_VERS("   core-version   : "),
    UPGRD_VERS("   upgrade-version: "),
    CREATE_MODE("   create-mode    : "),
    FIELDOPTION("   fieldOption    : "),
    DATA("   data           : "),
    DATA_MAPPING("   data-mapping   : "),
    DATA_TYPE("   datatype       : "),
    DDE_ACTION("      dde-action  : "),
    DDE_COMMAND("      dde-command : "),
    DDE_FILE("      dde-file    : "),
    DDE_ITEM("      dde-item    : "),
    DDE_SERVICE("      dde-service : "),
    DDE_TOPIC("      dde-topic   : "),
    AUTO_SERVER("      auto-server : "),
    AUTO_CLSID("      auto-clsId  : "),
    AUTO_ACTION("      auto-action : "),
    AUTO_VISIBLE("      auto-visible: "),
    AUTO_COM("      auto-COM    : "),
    DIRECT_SQL("      direct-sql  : "),
    ENCR_AL_SQL("      encrypt-sql : "),
    DEFAULT("   default        : "),
    DEFAULT_VUI("   default-vui    : "),
    DESCRIPTION("   description    : "),
    DISPLAY("   display        : "),
    DISPLAY_2("      display     : "),
    DISPLAY_PROPLIST("   display-prop   : "),
    DISPLAY_INSTANCE(" display-instance : "),
    DUP_ACTION("   dup-action     : "),
    PATTERN_MATCH("   pat-match      : "),
    REQUIRED_FIELDS("   req-fields     : "),
    ENABLE("   enable         : "),
    ENUM_VALUE("   enum-value     : "),
    ENUM_VALUE_NUM("   enum-value-num : "),
    ENUM_QRY_SCHEMA("   enum-qry-schema: "),
    ENUM_QRY_SERVER("   enum-qry-server: "),
    ENUM_QRY_QUERY("   enum-qry-query : "),
    ENUM_QRY_NAME("   enum-qry-name  : "),
    ENUM_QRY_NUM("   enum-qry-num   : "),
    TBLFLD_SCHEMA("tablefield-schema : "),
    TBLFLD_SERVER("tablefield-server : "),
    TBLFLD_QUERY("tablefield-query  : "),
    TBLFLD_NUMCOLS("tablefield-numcols: "),
    TBLFLD_MAXRET("tablefield-maxret : "),
    COLFLD_PARENT("colfield-parent   : "),
    COLFLD_DATAFIELD("colfield-datafield: "),
    COLFLD_DATATYPE("colfield-datatype : "),
    COLFLD_DATASOURCE("colfield-datasrc  : "),
    COLFLD_COLLENGTH("colfield-collength: "),
    ESCALATION_HOUR("   escl-hourmask  : "),
    ESCALATION_INT("   escl-interval  : "),
    ESCALATION_MIN("   escl-minute    : "),
    ESCALATION_MON("   escl-monthday  : "),
    ESCALATION_QRY("   escl-query     : "),
    ESCALATION_TMTYPE("   escl-tmType    : "),
    ESCALATION_WEEK("   escl-weekday   : "),
    EXPORT_VERS("   export-version : "),
    EXT_NAME("   ext-name       : "),
    EXT_FIELD("   ext-field      : "),
    EXT_TABLE("   ext-table      : "),
    FIELD_TYPE("   fieldtype      : "),
    FIELD_REF("      field-ref   : "),
    FILE_TYPE("      file-type   : "),
    FILTER_OP("   filter-op      : "),
    FILTER_ORD("   filter-order   : "),
    FILTER_QRY("   filter-query   : "),
    FOCUS("      focus       : "),
    FROM_SCHEMA("   from-schema    : "),
    FROM_SERVER("   from-server    : "),
    FULLTEXTOPTNS("   fulltext-optns : "),
    LITERAL_INDEXED(" literal-indexed : "),
    FUNC_CODES("   func-codes     : "),
    GET_LIST_FLDS("   get-list-flds  : "),
    HELP("   help-text      : "),
    ID("   id             : "),
    ID_2("      id          : "),
    IMAGE_CHECKSUM("   imageChecksum  : "),
    IMAGE_CONTENT("   imageContent   : "),
    IMAGE_SIZE("   imageSize      : "),
    IMAGE_TYPE("   imageType      : "),
    INDEX("   index          : "),
    JOIN_OPTION("      join-option : "),
    JOIN_PRIMARY("      primary     : "),
    JOIN_QRY("      join-query  : "),
    JOIN_SECONDARY("      secondary   : "),
    LABEL("   label          : "),
    LAST_CHANGED("   last-changed   : "),
    LENGTH_UNITS("   length-units   : "),
    LICENSE_TYPE("   licensetype      : "),
    LOG_FILE("      log-file    : "),
    MACRO_NAME("      macro-name  : "),
    MACRO_PARMS("      macro-parms : "),
    MACRO_TEXT("      macro-text  : "),
    MAP_FIELDID("      mapfield    : "),
    MAP_SCHEMA("      mapschema   : "),
    MAP_TYPE("   map-type       : "),
    MAPPING("   mapping        : "),
    MATCH_QUAL("   match-qual     : "),
    MAX_DATE("   maxDate        : "),
    MAX_LENGTH("   maxlength      : "),
    MAXSIZE("   maxsize        : "),
    MIN_DATE("   minDate        : "),
    ATTACH_TYPE("   attachtype     : "),
    MENU_STYLE("   menu-style     : "),
    MSG_NUM("      message-num : "),
    MSG_TEXT("      message-text: "),
    MSG_TYPE("      message-type: "),
    MSG_PANE("      message-pane: "),
    NAME("   name           : "),
    NOT_FIELDS("      notify-field: "),
    NOT_MECH("      notify-mech : "),
    NOT_PRIORITY("      notify-pri  : "),
    NOT_SUBJECT("      notify-subj : "),
    NOT_TEXT("      notify-text : "),
    NOT_USER("      notify-user : "),
    NOT_XREF("      notify-xref : "),
    NOT_BEHAVIOR("      notify-behvr: "),
    NOT_PERMISSION("      notify-perm : "),
    NOT_ADV_REPLY_TO("      notify-reply: "),
    NOT_ADV_FROM("      notify-from : "),
    NOT_ADV_CC("      notify-cc   : "),
    NOT_ADV_BCC("      notify-bcc  : "),
    NOT_ADV_ORG("      notify-org  : "),
    NOT_ADV_MAILBOX("      notify-mlbox: "),
    NOT_ADV_HDR_TMP("      notify-hdrtm: "),
    NOT_ADV_FTR_TMP("      notify-ftrtm: "),
    NOT_ADV_CNT_TMP("      notify-cnttm: "),
    NUM_FIELDS("   num-fields     : "),
    NUM_REFERENCES("   num-references : "),
    NUM_VUIS("   num-vuis       : "),
    STRUCTITEM_LIST("  struct-item-list: "),
    ENCR_TEXT("  encrypt-text    : "),
    CHECKSUM("  checksum        : "),
    OBJECT("   object         : "),
    OBJECT_PROP("   object-prop    : "),
    ENCR_OBJECT_PROP("  encrypt-obj-prop: "),
    OBJECT_PROP_INTERVAL("   interval       : "),
    FORM_SCHEMA_ROW_ID("   schema-row-identifier : "),
    GUID("   guid           : "),
    OPEN_DLG("   open-dialog    : "),
    OPEN_DLG_SERVER("      open-server : "),
    OPEN_DLG_SCHEMA("      open-schema : "),
    OPEN_DLG_VUI("      open-vui    : "),
    OPEN_DLG_BOX("      open-close  : "),
    OPEN_DLG_INPUT("      open-input  : "),
    OPEN_DLG_OUTPUT("      open-output : "),
    OPEN_DLG_WINMODE("      open-winmod : "),
    OPEN_DLG_TARGET("      open-target : "),
    OPEN_DLG_QUERY("      open-query  : "),
    OPEN_DLG_CONTINU("      open-continu: "),
    OPEN_DLG_SUPPRESS("      open-suppres: "),
    OPEN_DLG_MSG_TYPE("      open-msgtype: "),
    OPEN_DLG_MSG_NUM("      open-msgnum : "),
    OPEN_DLG_MSG_PANE("      open-msgpane: "),
    OPEN_DLG_MSG_TEXT("      open-msgtext: "),
    OPEN_DLG_POLLINT("      open-pollint: "),
    OPEN_DLG_RPTSTR("      open-rptstr : "),
    OPEN_DLG_SORTORD("      open-sortord: "),
    CALLGUIDE_SERVER("      call-server : "),
    CALLGUIDE_GUIDE("      call-guide  : "),
    CALLGUIDE_MODE("      call-mode   : "),
    CALLGUIDE_TABLEID("      call-tableid: "),
    CALLGUIDE_INPUT("      call-input  : "),
    CALLGUIDE_OUTPUT("      call-output : "),
    EXITGUIDE("      exit guide  : "),
    GOTOGUIDE("      goto guide  : "),
    WAIT("      wait        : "),
    GOTOACTION("      goto action : "),
    OPTION("   option         : "),
    OWNER("   owner          : "),
    CONTAINER_OWNER("   owning-obj     : "),
    CONTAINER_OWNER_NAME("   owning-obj-name: "),
    CONTAINER_OWNER_TYPE("   owning-obj-type: "),
    CONTAINER_NUM_OWNER("   num-owning-obj : "),
    PATTERN("   pattern        : "),
    PERMISSION("   permission     : "),
    PRECISION("   precision      : "),
    REFERENCE_GROUPS("   ref-groups     : "),
    QBE_MATCH_OP("   qbe-match-op   : "),
    CLOB_STORE_OPT("   clob-store-opt : "),
    PUSH_FIELD("      push-field  : "),
    SAMPLE_SERVER("      samp-server : "),
    SAMPLE_SCHEMA("      samp-schema : "),
    SAMPLE_GUIDE("      samp-guide  : "),
    ENCR_FIELDP("encrypt-push-field: "),
    RANGE_HIGH("   range-high     : "),
    RANGE_LOW("   range-low      : "),
    REFRESH_CODE("   refresh-code   : "),
    RETRY_TIME("   retry-time     : "),
    RTN_MAP_TYPE("   rtn-map-type   : "),
    RTN_MAPPING("   rtn-mapping    : "),
    RTN_EXCL_FLDS("rtn-exclude-fields: "),
    EXCL_FLDS("   exclude-fields : "),
    WK_CONN_TYPE("   wk-conn-type   : "),
    NEXT_FIELD_ID("   next-field-id  : "),
    SCHEMA_NAME("   schema-name    : "),
    SCHEMA_TYPE("   schema-type    : "),
    SCHEMA_SUBADM("   schema-admin   : "),
    SET_FIELD("      set-field   : "),
    ENCR_SET_FIELD(" encrypt-set-field: "),
    SMOPROP_LIST("   obj-props      : "),
    SORT_LIST("   sort-list      : "),
    TIMESTAMP("   timestamp      : "),
    TIMESTAMP_2("      timestamp   : "),
    TO_SCHEMA("   to-schema      : "),
    TO_SERVER("   to-server      : "),
    TRANSFER_MODE("   transfer-mode  : "),
    TYPE("   type           : "),
    UPDATE_CODE("   update-code    : "),
    VIEW_KEYFIELD("      key-field   : "),
    VIEW_NAME("      ext-table   : "),
    VIEW_QRY("      view-query  : "),
    VALUE("   value          : "),
    DISTRIB_TCOUNT("   thread-count   : "),
    DISTRIB_CONNECT("   connection     : "),
    VUI_LOCALE("   vui-locale     : "),
    VUI_TYPE("   vui-type       : "),
    ARCHIVEINFO("   archive        : "),
    ARCHIVEINFO_TIME("      arch-time   : "),
    ARCHIVEINFO_QRY("      arch-query  : "),
    ARCHIVEINFO_FROM("      arch-from   : "),
    ASSN_TO_FOLLOW_TYPE("   assoc-to-follow-type : "),
    ASSN_TO_FOLLOW("  assoc-to-follow : "),
    ASSN_SEL_TYPE("   assoc-sel-type : "),
    ASSN_SPECIFIC_LIST("     assoc-list   : "),
    ADD_ASSN_SPECIFIC_LIST("   add-assoc-list : "),
    FIELD_INHERITANCE_NUM_SOURCE_FORMS("   num-of-source-forms : "),
    FIELD_INHERITANCE_CORE_FIELDS_SOURCE_FORM("   core-fields-source-form : "),
    FIELD_INHERITANCE_FORM_OVERLAY_GROUP("   field-inheritance-overlay-group : "),
    FIELD_INHERITANCE_FORM_INHERITING_WORKFLOW("   is-inheriting-workflow : "),
    FIELD_INHERITANCE_FORM_INHERITING_PERMISSIONS("   is-inheriting-permissions : "),
    FIELD_INHERITANCE_FORM_INHERITING_ASSOCIATIONS("   is-inheriting-associations : "),
    FIELD_INHERITANCE_FORM_INHERITING_AUDIT_OPTIONS("   is-inheriting-audit-options : "),
    FIELD_INHERITANCE_FIELD_SOURCE_SCHEMA("   source-schema : "),
    FIELD_INHERITANCE_IS_INHERITABLE("   is-form-inheritable : "),
    FIELD_INHERITANCE_IS_CREATE_ENTRY_ALLOWED("   is-create-entry-allowed : "),
    FIELD_INHERITANCE_IS_SHARED_DATA_FORM("   is-shared-data-form : "),
    LC_STRING_BUNDLE("   bundle         : "),
    LC_STRING_LOCALE("   locale         : "),
    LC_STRING_STRINGID("   stringId       : "),
    LC_STRING_TEXT("   string-text    : "),
    LC_STRING_OWNER_OBJECT("   owner-objects  : "),
    ARCHIVEINFO_MODIFIEDTIME_QUALIFIER("    age-qualifier : "),
    ARCHIVEINFO_MODIFIEDTIME_QUALIFIER_FIELD("   age-qual-field : "),
    ARCHIVEINFO_APPEAR_IN_ARCHIVE_POLICY(" appr-arch-policy : "),
    ARCHIVEINFO_DESCRIPTION("     description  : "),
    AUDITINFO("   audit          : "),
    AUDITINFO_QRY("      audt-query  : "),
    AUDITINFO_FORM("      audt-form   : "),
    ERRORHANDLER_OPTIONS("   errhandler-opt : "),
    ERRORHANDLER_NAME("   errhandler-name: "),
    ASSN_PRIMARY_FORM("   primary-form   : "),
    ASSN_PRIMARY_FORM_QUAL("  primary-frm qry : "),
    ASSN_SECONDARY_FORM("   secondary-form : "),
    ASSN_SECONDARY_FORM_QUAL(" secondry-frm qry : "),
    ASSN_TYPE("    assn-type     : "),
    ASSN_ENFORCEMENT(" assn-enforcement : "),
    ASSN_CARDINALITY(" assn-cardinality : "),
    ASSN_PRIMARY_FORM_MODALITY(" assn-primary-form-modality : "),
    ASSN_ASSOCIATION_FORM(" association-form : "),
    ASSN_ASSOCIATION_FORM_QUAL("  assn-form query : "),
    ASSN_PRIMARY_KEY_FIELD("  primary-key-fld : "),
    ASSN_FOREIGN_KEY_FIELD("  foreign-key-fld : "),
    ASSN_DESCRIPTION(" assn-description : "),
    POLLING("   polling        : "),
    POLLING_INTERVAL(" polling-interval : "),
    ASSN_PRIMARY_TO_SECONDARY_NAME("      primary-to-secondary-name   : "),
    ASSN_SECONDARY_TO_PRIMARY_NAME("      secondary-to-primary-name   : "),
    DEFINITION("   definition     : "),
    BUNDLE_VERSION("   bundle-version : "),
    DSO_ASSOC_TAGS("      dso-assn-tags   : ");

    private final String label;
    private static final Map<String, DefItemLabel> LOOKUP = new HashMap<>(384);

    static {
        for (DefItemLabel l : values()) LOOKUP.put(l.label.trim(), l);
    }

    DefItemLabel(String label) {
        this.label = label;
    }

    public String label() {
        return label;
    }

    /** tag must already be trimmed (leading/trailing whitespace only - internal padding is significant). */
    public static DefItemLabel of(String trimmedTag) {
        return LOOKUP.get(trimmedTag);
    }
}
